---
################
system:
  ################
  structure1:
    name: "neopentane"
    tlc: "UNL"
    waterbox:
      dirname: "waterbox"
      psf_file_name: "step3_charmm2omm"
      crd_file_name: "step3_charmm2omm"
      rst_file_name: "step4_equilibration"
      simulation_parameter: "step5_production.inp"
      intermediate-filename: "lig_in_waterbox"
    vacuum:
      dirname: "vacuum"
      psf_file_name: "step3_charmm2omm"
      crd_file_name: "step3_charmm2omm"
      rst_file_name: "step4_equilibration"
      simulation_parameter: "step5_production.inp"
      intermediate-filename: "lig_in_vacuum"

  structure2:
    name: "methane"
    tlc: "LIG"
    waterbox:
      dirname: "waterbox"
      psf_file_name: "step3_charmm2omm"
      crd_file_name: "step3_charmm2omm"
      rst_file_name: "step4_equilibration"
      simulation_parameter: "step5_production.inp"
      intermediate-filename: "lig_in_waterbox"
    vacuum:
      dirname: "vacuum"
      psf_file_name: "step3_charmm2omm"
      crd_file_name: "step3_charmm2omm"
      rst_file_name: "step4_equilibration"
      simulation_parameter: "step5_production.inp"
      intermediate-filename: "lig_in_vacuum"

################
simulation:
  ################
  parameters:
    nstep: 1000000
    nstdcd: 1000
    nstout: 5000
    dt: 0.001
    switch: "vswitch"
  GPU: True
  free-energy-type: "solvation-free-energy"
################
